Add ChangeStartupMsg test for platform test
canonical/edgex-snap-testing pull request #94
Opened 2022-07-25 12:36 UTC by MonicaisHer

resolves #78

2022-07-25 16:28 UTC, farshidtz requested changes
It looks good overall. I've commented regarding some minor issues.

As a discussion point, I am thinking if this test should be default for all suites, or turned into a common test and ran selectively. It is relevant for other multi-service snaps too, currently also edgex-device-usb, even though it doesn't cause a conflict like for edgexfoundry.

2022-07-26 11:15 UTC, farshidtz commented
Actually the test will pass as long as the script in command chain exports any variable with that value. For example, you can set X=<message> and it will still pass.

I think we should be looking for the `msg=<message>`.

```
2022-07-26T13:11:27+02:00 edgex-device-mqtt.device-mqtt[44970]: ++ export SERVICE_STARTUPMSG=test
...
2022-07-26T13:11:27+02:00 edgex-device-mqtt.device-mqtt[44970]: level=INFO ts=2022-07-26T11:11:27.153627777Z app=device-mqtt source=variables.go:352 msg="Variables override of 'Service.StartupMsg' by environment variable: SERVICE_STARTUPMSG=test"
...
2022-07-26T13:12:27+02:00 edgex-device-mqtt.device-mqtt[44970]: level=INFO ts=2022-07-26T11:12:27.199253366Z app=device-mqtt source=message.go:55 msg=test
```

2022-07-26 11:22 UTC, farshidtz commented on test/suites/edgexfoundry/config_test.go
> +	utils.SnapSet(t, platformSnap, "app-options", "true")
We turn it on to enable app options, which are being tested.

2022-07-26 11:31 UTC, farshidtz commented on test/suites/edgexfoundry/config_test.go
> +	require.True(t, checkStartupMsg(t, supportSchedulerService, defaultStartupMsg))
The error message is hard to follow when this fails. Better add a message instead of comment in code.

2022-07-26 12:04 UTC, farshidtz commented
@MonicaisHer okay with the changes?

2022-07-26 12:05 UTC, farshidtz approved these changes

2022-07-26 12:41 UTC, MonicaisHer commented
> @MonicaisHer okay with the changes?

thanks for your changes, the changes look great!

2022-07-26 12:43 UTC, merged